---
sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - echo "Printing node version..."
  - node -v 
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.1
  - export PATH="$HOME/.yarn/bin:$PATH"
  - export BRANCH="${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
  - export TZ="America/Sao_Paulo"
  - git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
  - git fetch --all
  - git checkout "$BRANCH"
install:
  - yarn install --frozen-lockfile;
  - yarn build
script:
  - yarn lint .
  - yarn lint.test .
  - travis_wait yarn coverage