---
sudo: false
language: node_js
node_js:
  - '8'
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
  - export PATH="$HOME/.yarn/bin:$PATH"
  - export BRANCH="${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
  - git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
  - git fetch --all
  - git checkout "$BRANCH"
install:
  - yarn --frozen-lockfile
  - lerna bootstrap
  - lerna link
  - npx flow-typed install
script:
  - yarn lint .
  - yarn lint.test .
  - yarn typecheck
  - yarn coverage
after_success:
  - lerna run build
  - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > /home/travis/.npmrc
  - echo "@crave:registry=https://registry.npmjs.org/" >> /home/travis/.npmrc
  - if [ $BRANCH == "master" ]; then
      git config user.name "Travis CI" || travis_terminate 1;
      git config user.email "travis@cravefood.services" || travis_terminate 1;
      git remote set-url origin https://${GH_TOKEN}@github.com/CraveFood/farmblocks.git || travis_terminate 1;
      lerna publish --yes || travis_terminate 1;
    else
      lerna publish --canary --yes || travis_terminate 1;
    fi
