sudo: false
language: node_js
node_js:
  - "7.10.0"

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      script: npm test

notifications:
  email:
    on_success: change
    on_failure: change
