// flow-typed signature: a93c66741fb6b803435bee25bc95d88f
// flow-typed version: <<STUB>>/@crave/farmblocks-text_v1.2.0-alpha.d467d10d/flow_v0.63.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@crave/farmblocks-text'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@crave/farmblocks-text' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@crave/farmblocks-text/lib/components/Text' {
  declare module.exports: any;
}

declare module '@crave/farmblocks-text/lib/constants/paragraphLineHeights' {
  declare module.exports: any;
}

declare module '@crave/farmblocks-text/lib/index' {
  declare module.exports: any;
}

declare module '@crave/farmblocks-text/lib/styledComponents/Text' {
  declare module.exports: any;
}

// Filename aliases
declare module '@crave/farmblocks-text/lib/components/Text.js' {
  declare module.exports: $Exports<'@crave/farmblocks-text/lib/components/Text'>;
}
declare module '@crave/farmblocks-text/lib/constants/paragraphLineHeights.js' {
  declare module.exports: $Exports<'@crave/farmblocks-text/lib/constants/paragraphLineHeights'>;
}
declare module '@crave/farmblocks-text/lib/index.js' {
  declare module.exports: $Exports<'@crave/farmblocks-text/lib/index'>;
}
declare module '@crave/farmblocks-text/lib/styledComponents/Text.js' {
  declare module.exports: $Exports<'@crave/farmblocks-text/lib/styledComponents/Text'>;
}
