// flow-typed signature: f0d911fa5d566f416ea76b92cf60e758
// flow-typed version: <<STUB>>/@crave/farmblocks-tooltip_v0.2.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@crave/farmblocks-tooltip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@crave/farmblocks-tooltip" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@crave/farmblocks-tooltip/lib/Tooltip" {
  declare module.exports: any;
}

declare module "@crave/farmblocks-tooltip/lib/index" {
  declare module.exports: any;
}

declare module "@crave/farmblocks-tooltip/lib/styledComponents/Tooltip" {
  declare module.exports: any;
}

// Filename aliases
declare module "@crave/farmblocks-tooltip/lib/Tooltip.js" {
  declare module.exports: $Exports<"@crave/farmblocks-tooltip/lib/Tooltip">;
}
declare module "@crave/farmblocks-tooltip/lib/index.js" {
  declare module.exports: $Exports<"@crave/farmblocks-tooltip/lib/index">;
}
declare module "@crave/farmblocks-tooltip/lib/styledComponents/Tooltip.js" {
  declare module.exports: $Exports<
    "@crave/farmblocks-tooltip/lib/styledComponents/Tooltip"
  >;
}
