const linkTypes = {
  PRIMARY: "PRIMARY",
  DISABLED: "DISABLED",
  NEUTRAL: "NEUTRAL",
  ROW_TITLE: "ROW_TITLE",
  EXTERNAL_DEFAULT: "EXTERNAL_DEFAULT",
  EXTERNAL_ADDRESS: "EXTERNAL_ADDRESS",
  EXTERNAL_ADDRESS_WHITE: "EXTERNAL_ADDRESS_WHITE",
  EXTERNAL_ADDRESS_MINI: "EXTERNAL_ADDRESS_MINI",
  EXTERNAL_ADDRESS_MINI_WHITE: "EXTERNAL_ADDRESS_MINI_WHITE"  
};

module.exports = linkTypes;