import {
  CARBON,
  LETTUCE,
  STRAWBERRY,
  INDIGO_MILK_CAP,
  GREY_32,
  OYSTER
} from "./colors";

module.exports = {
  NORMAL: CARBON,
  NEUTRAL: OYSTER,
  POSITIVE: LETTUCE,
  NEGATIVE: STRAWBERRY,
  FEATURED: INDIGO_MILK_CAP,
  SUBTLE: GREY_32,
  WHITE: "white"
};
