const BUTTON_TYPES = {
  PRIMARY: "PRIMARY",
  NEUTRAL: "NEUTRAL",
  SECONDARY: "SECONDARY",
  NEGATIVE: "NEGATIVE",
  CLOSED: "CLOSED",
  POSITIVE: "POSITIVE",
  OFF_NEUTRAL: "OFF_NEUTRAL"
};

module.exports = BUTTON_TYPES;
